name: my_dbt_project
version: '1.0'

config-version: 2
profile: default

model-paths: ["models"]  # This points to the models folder

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_dbt_project:
    +materialized: view
