name: my_dbt_project
version: '1.0'

config-version: 2
profile: default

model-paths: ["models"]  # This points to the models folder

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_dbt_project:
    +materialized: table
  staging:  # This applies to all models in the 'staging' directory
    +schema: "staging"  # Models in this directory will go to 'YOUTUBE.STAGING' if the profiles.yml is correctly configured
  raw:
    +schema: "raw"  # Models in this directory will go to 'YOUTUBE.RAW'
