name: my_dbt_project
version: '1.0'

config-version: 2
profile: default

model-paths: ["models"]  # This points to the models folder

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  YOUTUBE:  # This is the top-level project namespace, which is usually the same as your project name
    +materialized: table  # Default materialization for all models

  staging:  # This refers to the "staging" models folder inside the "models" directory
    +schema: "YOUTUBE.STAGING"  # Models in this folder will be placed in the "YOUTUBE.STAGING" schema

  raw:  # This refers to the "raw" models folder inside the "models" directory
    +schema: "raw"  # Models in this folder will be placed in the "raw" schema
